### ISSUE TITLE
nil value

### ISSUE THREAD

**Issue by BluePiru** [madScripting/TurtleWoW-RelarPallyPower#1]
![image](https://github.com/madScripting/TurtleWoW-RelarPallyPower/assets/81178709/eb27d230-bf21-472a-91c7-723cf6d8edd3)

Same Issue as with the other PalyPower

**Comment by madScripting** [comment]
A bad version of PallyPower previously installed corrupted your SavedVariable file.
You have to delete those files manually, then start your wow client:

Go in <WoWDir>\WTF\Account\
Search for "pallypower" (with the windows search bar)
delete all the files that are found (should all be .lua and l.ua.bak)
